### ISSUE TITLE
Grouping hierarchy label empty for selection grouping 

### ISSUE THREAD

**Issue by katush** [lineupjs/lineup_app#34] opened 2018-11-19 15:54 UTC
If grouping by selection is active, the corresponding grouping hierarchy panel is missing a label (it should say something like grouping by selection):

![image](https://user-images.githubusercontent.com/8986080/48715987-9a7b2f00-ec16-11e8-95ab-1e26b692e947.png)

**Comment by sgratzl** [comment] 2018-12-04 19:02
Duplicate of https://github.com/lineupjs/lineupjs/issues/110

**Closed as completed by sgratzl** 2018-12-04 19:02 UTC
Labels: duplicate
